-- sales-analytics-dashboard-v2 (mid-Stage-2 follow-up)
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run
--
-- Retires the "run a test as trigger='cron', then UPDATE it to 'manual'
-- afterward" pattern used during core-v1/dashboard-v2 verification - it
-- rewrites sync history after the fact, which Jack correctly flagged.
-- Adds a real third trigger value, 'test', so verification runs are
-- honestly labeled from insert onward and never touched again.
--
-- 'test' runs are exempt from the manual daily cap and cooldown for free -
-- api/sales/sync.js's checkManualLimits() only runs `if (trigger ===
-- 'manual')`, so trigger='test' already skips it with zero code change.
-- api/sales/routes.js's runsRoute now excludes trigger='test' so it never
-- appears as "last synced" in the UI.
--
-- The 5 rows relabeled under the old pattern (ids below, all already
-- trigger='manual', error_text='test-run relabeled') are left exactly as
-- they are, per Jack's explicit instruction - this migration only changes
-- what's allowed going forward, it does not touch existing rows:
--   6974ee48-a5df-4600-9e6a-67cb899b945e
--   2505d3fd-37c2-4739-8c36-fecc5cdd9076
--   ffce5864-c3cf-465f-91c4-fadce2ab1ac7
--   109e0eef-99a9-41f8-b613-00f545cec3c6
--   45e4b0e9-96b0-4b83-974b-7ba3402b4e41
--
-- The existing check constraint's name isn't assumed - it was declared
-- inline in the original CREATE TABLE, so this looks it up by definition
-- text rather than guessing the autogenerated name, and drops only that
-- one constraint.
do $$
declare
  found_name text;
begin
  select conname into found_name
  from pg_constraint
  where conrelid = 'sales_sync_runs'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) like '%trigger%';
  if found_name is not null then
    execute format('alter table sales_sync_runs drop constraint %I', found_name);
  end if;
end $$;

alter table sales_sync_runs
  add constraint sales_sync_runs_trigger_check
  check (trigger in ('cron', 'manual', 'test'));

-- Self-check - must show the new constraint definition including 'test'.
select conname, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'sales_sync_runs'::regclass
  and conname = 'sales_sync_runs_trigger_check';
